default-config: &default-config
  docker:
    - image: circleci/node:10
  working_directory: ~/personal-site

version: 2
jobs:
  build:
    <<: *default-config
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - deps-{{ checksum "package.json" }}-
            - deps-
      - run:
          name: Install dependencies
          command: |
            npm install --no-save
      - save_cache:
          key: deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Install dependencies
          command: |
            npm install --no-save

  deploy:
    <<: *default-config
    steps:
      - run:
          name: Set Git User
          command: |
            git config user.name "javiguajardo"
            git config user.email "f.javi.guajardo@gmail.com"
      - run: 
          name: Deploy to GH pages
          command: npm run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop        
