version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    filters:
      branches:
        only: master
    working_directory: ~/personal-site
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            - deps-{{ checksum "package.json" }}-
            - deps-
      - run:
          name: Install dependencies
          command: |
            npm install --no-save
      - save_cache:
          key: deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: 
          name: Gatsby deploy
          command: npm run deploy
